#!/bin/sh -e
# result of:
# pwgen 32 -1 | gpg --encrypt --armor -r <key> -r <key> -r <key>
# create a vault with `ansible-vault create foo.yml`,
# and edit with `ansible-vault edit foo.yml`

gpg2 -q --decrypt <<-EOF
-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQEMA+SmzwCWgUiVAQf9Ell1V1RtjxJ1aS8FpxKxW3d/kgY+Mbo9YBAxDpem9utM
vtS1o3k/P1SZddQgjFV2QJ0EbFf8J9wlLFfwhwJK3x6ogSh/mvSNH3aVniKa6BdH
4m34foaQWvNHHbabXjIFmwutQaPum8YbBldH4miwzuQlMRNPZ6d/0+KsLXp8NPU8
AmGGlH8IXHf5F/dzqNoYQVA1e3WghEtjBUqmQsQKQ5gFvxO1ZPOMTFjwEywkn231
Qp8yLLUDNQEPmdVRRtiqLzGPv+An4BkYo+Q2/MYucML2XatAJ1Thk6eTA3iy49H7
/tHj90END7/lCPm18MO/O0iDqsotpyuHqOP+lX73F4UBDAP3dUb1YeigqAEIAM4d
SyQlZSfNj/4i2zv0W7AVd5RkRJMy7C9hNnQsJOLL6GQCyHD2f7KYis3cVwSTJB2r
xlYyiH+xsje1UF2adW8aGNn3wN+TDhmYuBjTSUoJIbrTNdMaL3XatSvDKSY83RRe
BDo5BhwdXKExExhiZVkyaWu9HAQ/LS5aLyeGq6g+RmXwVwUZD86TS4oaXc8VuP4u
ZoNhGmNdayO2jVxexIZbcYhRr+HREZcVmET3uzL+25cmO0I/e0ucGu5qh77K3uPQ
f8bVkPaetUoiU9Xac/0elIa6P7x1cDtm2tRWIcH4yM3MUflNGA0NJ4kF1y3jXJOr
frEH8qYh4NoQ2OBCXUXSRQG/OhAjhkxdZemfXtRbuFIBZATbVp1Du2hbK5eBbgJc
mptLnRC8TfJ/UTu3BMP1+PK9xY2cOFim7N0bR/NmdgA8s01U9A==
=0lKD
-----END PGP MESSAGE-----
EOF
